version: '3.8'

services:
  # Spring Boot
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    networks:
      - app-network

  # React
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
